apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "baa.fullname" . }}
  labels:
    {{- include "baa.labels" . | nindent 4 }}
data:
  LOG_LEVEL: {{ .Values.common.logLevel | quote }}

  API_GATEWAY_AUTH_SERVICE_URL: {{ printf "http://%s:%d" (include "baa.serviceName" (dict "root" . "component" "auth")) (int .Values.services.auth.service.port) | quote }}
  API_GATEWAY_ASSISTANT_SERVICE_URL: {{ printf "http://%s:%d" (include "baa.serviceName" (dict "root" . "component" "assistant")) (int .Values.services.assistant.service.port) | quote }}
