apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "baa.fullname" . }}
  labels:
    {{- include "baa.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "baa.fullname" . }}
  labels:
    {{- include "baa.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "baa.fullname" . }}
  labels:
    {{- include "baa.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "baa.fullname" . }}
roleRef:
  kind: Role
  name: {{ include "baa.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
