{{- if .Values.vpa.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "baa.serviceName" (dict "root" . "component" "gateway") }}
  labels:
    {{- include "baa.componentLabels" (dict "component" "gateway" "root" .) | nindent 4 }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "baa.serviceName" (dict "root" . "component" "gateway") }}
  updatePolicy:
    updateMode: {{ .Values.vpa.updateMode | quote }}
{{- end }}
