global:
  scrape_interval: 15s

scrape_configs:
  - job_name: gateway
    metrics_path: /metrics
    static_configs:
      - targets: ["gateway:8000"]

  - job_name: auth_service
    metrics_path: /metrics
    static_configs:
      - targets: ["auth:8001"]

  - job_name: assistant_service
    metrics_path: /metrics
    static_configs:
      - targets: ["assistant:8002"]
